repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 1.96.3 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_tfsec
    - id: terraform_validate
    - id: tfupdate
